-- Create accounts table with all fields including visual style fields
CREATE TABLE IF NOT EXISTS accounts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  website_url TEXT NOT NULL,
  industry TEXT NOT NULL,
  description TEXT,
  goals TEXT,
  target_audience TEXT,
  tone TEXT,
  color_scheme TEXT,
  monthly_post_count INTEGER DEFAULT 20,
  keywords TEXT,
  text_length INTEGER DEFAULT 150,
  use_emojis BOOLEAN DEFAULT true,
  website_analysis TEXT,
  products TEXT,
  expertise TEXT,
  blog_topics TEXT,
  company_values TEXT,
  client_types TEXT,
  visual_style TEXT,
  image_style TEXT,
  design_elements TEXT,
  brand_personality TEXT,
  layout_style TEXT,
  facebook_url TEXT DEFAULT '',
  instagram_url TEXT DEFAULT '',
  youtube_url TEXT DEFAULT '',
  twitter_url TEXT DEFAULT '',
  linkedin_url TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create posts table with image_prompt field
CREATE TABLE IF NOT EXISTS posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  hashtags TEXT[] DEFAULT '{}',
  image_url TEXT,
  image_prompt TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'published')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_posts_account_id ON posts(account_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);
CREATE INDEX IF NOT EXISTS idx_accounts_created_at ON accounts(created_at);

-- Insert sample data with all new fields
INSERT INTO accounts (
  name, 
  website_url, 
  industry, 
  description, 
  goals, 
  target_audience, 
  tone, 
  color_scheme, 
  monthly_post_count, 
  keywords,
  text_length,
  use_emojis,
  website_analysis,
  products,
  expertise,
  blog_topics,
  company_values,
  client_types,
  visual_style,
  image_style,
  design_elements,
  brand_personality,
  layout_style,
  facebook_url,
  instagram_url,
  youtube_url,
  twitter_url,
  linkedin_url
) VALUES 
(
  'TechStart Inc.',
  'https://techstart.example.com',
  'technology',
  'A cutting-edge startup focused on AI solutions',
  'Increase brand awareness and attract potential investors',
  'Tech enthusiasts, investors, and early adopters',
  'professional',
  'Blue and white',
  25,
  'AI, technology, innovation, startup',
  150,
  true,
  'Technology startup with focus on AI solutions and professional communication style.',
  'AI software, automation tools, consulting services',
  'Artificial intelligence, machine learning, business automation',
  'AI trends, technology insights, automation benefits',
  'Innovation, reliability, cutting-edge solutions',
  'Startups, enterprises, tech companies',
  'modern, clean, minimalist',
  'professional photography, clean product shots',
  'sharp lines, gradients, modern typography',
  'innovative, reliable, forward-thinking',
  'grid-based, structured, responsive',
  '',
  '',
  '',
  '',
  ''
),
(
  'Healthy Bites Cafe',
  'https://healthybites.example.com',
  'food',
  'Organic, locally-sourced healthy food restaurant',
  'Drive foot traffic and promote healthy eating',
  'Health-conscious individuals, local community',
  'casual',
  'Green and earth tones',
  20,
  'healthy food, organic, local, nutrition',
  150,
  true,
  'Local restaurant focused on healthy, organic food with casual, community-oriented approach.',
  'Fresh meals, smoothie bowls, organic salads, catering',
  'Organic cooking, local sourcing, nutritional planning',
  'Healthy recipes, local ingredients, seasonal menus',
  'Health, sustainability, community support',
  'Health-conscious diners, families, local community',
  'warm, inviting, rustic',
  'food photography, warm lighting, natural textures',
  'warm colors, organic shapes, cozy atmosphere',
  'welcoming, authentic, community-focused',
  'organic, menu-focused, cozy',
  '',
  '',
  '',
  '',
  ''
)
ON CONFLICT DO NOTHING;
